### ISSUE TITLE
[BUG]:  RuntimeError: setStorage: sizes when training to finetune mT5 model

### ISSUE THREAD

**Issue by theblackcat102** [hpcaitech/ColossalAI#2145]
### 🐛 Describe the bug

I am trying to train Google mT5 model ( I have tried mt5-small and mt5-large ). My model had a runtime error during the feedforward phase in training.

The error had something to do with setStorage problem, which I suspect it's down to a bug in custom cuda code?

```
RuntimeError: setStorage: sizes [1024, 2816], strides [1, 1024], storage offset 42737152, and itemsize 2 requiring a storage size of 91241472 are out of bounds for storage of size 0
```

More specifically:
```
copycat/env/lib/python3.8/site-packages/transformers/tokenization_utils_base.py:2354: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(
torch.Size([2, 130]) torch.Size([2, 130]) torch.Size([2, 319])
torch.Size([2, 130, 1024])
torch.Size([2, 130, 1024])
torch.Size([2, 130, 1024])
torch.Size([2, 130, 1024])
  0%|          | 0/25100 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "colossalai_baseline.py", line 150, in <module>
    main()
  File "colossalai_baseline.py", line 140, in main
    outputs = model(batch['input_ids'], batch['attention_mask'], batch['decoder_input_ids'])
  File "copycat/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "copycat/env/lib/python3.8/site-packages/colossalai/nn/parallel/data_parallel.py", line 263, in forward
    outputs = self.module(*args, **kwargs)
  File "copycat/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "colossalai_baseline.py", line 68, in forward
    return self.model(input_ids=input_ids, attention_mask=attention_mask, decoder_input_ids=decoder_input_ids)[0]
  File "copycat/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "copycat/env/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py", line 1612, in forward
    encoder_outputs = self.encoder(
  File "copycat/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "copycat/env/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py", line 1028, in forward
    layer_outputs = checkpoint(
  File "copycat/env/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 235, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "copycat/env/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 96, in forward
    outputs = run_function(*args)
  File "copycat/env/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py", line 1024, in custom_forward
    return tuple(module(*inputs, use_cache, output_attentions))
  File "copycat/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "copycat/env/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py", line 726, in forward
    hidden_states = self.layer[-1](hidden_states)
  File "copycat/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "copycat/env/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py", line 329, in forward
    forwarded_states = self.DenseReluDense(forwarded_states)
  File "copycat/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "copycat/env/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py", line 308, in forward
    hidden_gelu = self.act(self.wi_0(hidden_states))
  File "copycat/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "copycat/env/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
  File "copycat/env/lib/python3.8/site-packages/colossalai/tensor/colo_tensor.py", line 183, in __torch_function__
    ret = func(*args, **kwargs)
  File "copycat/env/lib/python3.8/site-packages/colossalai/nn/_ops/linear.py", line 171, in colo_linear
    return colo_linear_imp(input_tensor, weight, bias)
  File "copycat/env/lib/python3.8/site-packages/colossalai/nn/_ops/linear.py", line 76, in colo_linear_imp
    ret_tensor = ColoTensor.from_torch_tensor(F.linear(input_tensor, weight, bias), spec=ColoTensorSpec(pg))
RuntimeError: setStorage: sizes [1024, 2816], strides [1, 1024], storage offset 42737152, and itemsize 2 requiring a storage size of 91241472 are out of bounds for storage of size 0
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2335161) of binary: copycat/env/bin/python
```

I have tried the GPT example which run perfectly without any issues. So I think the issue has to do with a different architecture design.

You can check my fullcode here : [https://github.com/theblackcat102/copycat/blob/master/colossalai_baseline.py](https://github.com/theblackcat102/copycat/blob/master/colossalai_baseline.py)

### Environment

CUDA 11.3
Python 3.8.15
Colossal package version : 0.1.12+torch1.12cu11.3

**Comment by feifeibear** [comment]
Could you please update the [colossalai_baseline.py](https://github.com/theblackcat102/copycat/blob/master/colossalai_baseline.py) using synthetic data (rand generated)? I can not download the dataset.

<img width="1727" alt="image" src="https://user-images.githubusercontent.com/5706969/208336780-23d59a5f-a39a-4172-9652-320bbff94e47.png">

**Comment by theblackcat102** [comment]
@feifeibear  My bad, here's a [test code](https://github.com/theblackcat102/copycat/blob/master/colossalai_test.py) for debugging, just git pull my repo and you should see the update

```
colossalai run --nproc_per_node 1 colossalai_test.py
```

**Comment by feifeibear** [comment]
/home/lcfjr/miniconda3/envs/dtensor/lib/python3.8/site-packages/transformers/convert_slow_tokenizer.py:446: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
[12/22/22 15:27:53] INFO     colossalai - colossalai - INFO:
                             /home/lcfjr/codes/ColossalAI/colossalai/context/par
                             allel_context.py:521 set_device
                    INFO     colossalai - colossalai - INFO: process rank 0 is
                             bound to device 0
[12/22/22 15:27:54] INFO     colossalai - colossalai - INFO:
                             /home/lcfjr/codes/ColossalAI/colossalai/context/par
                             allel_context.py:557 set_seed
                    INFO     colossalai - colossalai - INFO: initialized seed on
                             rank 0, numpy: 1024, python random: 1024,
                             ParallelMode.DATA: 1024, ParallelMode.TENSOR:
                             1024,the default parallel seed is
                             ParallelMode.DATA.
                    INFO     colossalai - colossalai - INFO:
                             /home/lcfjr/codes/ColossalAI/colossalai/initialize.
                             py:117 launch
                    INFO     colossalai - colossalai - INFO: Distributed
                             environment is initialized, data parallel size: 1,
                             pipeline parallel size: 1, tensor parallel size: 1
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /data2/users/lcfjr/codes/copycat/colossalai_test.py:145 in <module>          │
│                                                                              │
│   142 │   torch.cuda.synchronize()                                           │
│   143                                                                        │
│   144 if __name__ == '__main__':                                             │
│ ❱ 145 │   main()                                                             │
│   146                                                                        │
│                                                                              │
│ /data2/users/lcfjr/codes/copycat/colossalai_test.py:91 in main               │
│                                                                              │
│    88 │   logger = get_dist_logger()                                         │
│    89 │                                                                      │
│    90 │   model_id = "google/mt5-small"                                      │
│ ❱  91 │   model = AutoModelForSeq2SeqLM.from_pretrained(model_id)            │
│    92 │   tokenizer = AutoTokenizer.from_pretrained(model_id)                │
│    93 │   tokenizer.add_special_tokens({'sep_token': '<sep>'})               │
│    94 │   generator = gen_batch(tokenizer, model)                            │
│                                                                              │
│ /home/lcfjr/miniconda3/envs/dtensor/lib/python3.8/site-packages/transformers │
│ /models/auto/auto_factory.py:463 in from_pretrained                          │
│                                                                              │
│   460 │   │   │   )                                                          │
│   461 │   │   elif type(config) in cls._model_mapping.keys():                │
│   462 │   │   │   model_class = _get_model_class(config, cls._model_mapping) │
│ ❱ 463 │   │   │   return model_class.from_pretrained(                        │
│   464 │   │   │   │   pretrained_model_name_or_path, *model_args, config=con │
│   465 │   │   │   )                                                          │
│   466 │   │   raise ValueError(                                              │
│                                                                              │
│ /home/lcfjr/miniconda3/envs/dtensor/lib/python3.8/site-packages/transformers │
│ /modeling_utils.py:2276 in from_pretrained                                   │
│                                                                              │
│   2273 │   │   │   init_contexts.append(init_empty_weights())                │
│   2274 │   │                                                                 │
│   2275 │   │   with ContextManagers(init_contexts):                          │
│ ❱ 2276 │   │   │   model = cls(config, *model_args, **model_kwargs)          │
│   2277 │   │                                                                 │
│   2278 │   │   if load_in_8bit:                                              │
│   2279 │   │   │   from .utils.bitsandbytes import get_keys_to_not_convert,  │
│                                                                              │
│ /home/lcfjr/miniconda3/envs/dtensor/lib/python3.8/site-packages/transformers │
│ /models/t5/modeling_t5.py:1486 in __init__                                   │
│                                                                              │
│   1483 │   │   encoder_config.is_decoder = False                             │
│   1484 │   │   encoder_config.use_cache = False                              │
│   1485 │   │   encoder_config.is_encoder_decoder = False                     │
│ ❱ 1486 │   │   self.encoder = T5Stack(encoder_config, self.shared)           │
│   1487 │   │                                                                 │
│   1488 │   │   decoder_config = copy.deepcopy(config)                        │
│   1489 │   │   decoder_config.is_decoder = True                              │
│                                                                              │
│ /home/lcfjr/miniconda3/envs/dtensor/lib/python3.8/site-packages/transformers │
│ /models/t5/modeling_t5.py:848 in __init__                                    │
│                                                                              │
│    845 │   │   self.is_decoder = config.is_decoder                           │
│    846 │   │                                                                 │
│    847 │   │   self.block = nn.ModuleList(                                   │
│ ❱  848 │   │   │   [T5Block(config, has_relative_attention_bias=bool(i == 0) │
│    849 │   │   )                                                             │
│    850 │   │   self.final_layer_norm = T5LayerNorm(config.d_model, eps=confi │
│    851 │   │   self.dropout = nn.Dropout(config.dropout_rate)                │
│                                                                              │
│ /home/lcfjr/miniconda3/envs/dtensor/lib/python3.8/site-packages/transformers │
│ /models/t5/modeling_t5.py:848 in <listcomp>                                  │
│                                                                              │
│    845 │   │   self.is_decoder = config.is_decoder                           │
│    846 │   │                                                                 │
│    847 │   │   self.block = nn.ModuleList(                                   │
│ ❱  848 │   │   │   [T5Block(config, has_relative_attention_bias=bool(i == 0) │
│    849 │   │   )                                                             │
│    850 │   │   self.final_layer_norm = T5LayerNorm(config.d_model, eps=confi │
│    851 │   │   self.dropout = nn.Dropout(config.dropout_rate)                │
│                                                                              │
│ /home/lcfjr/miniconda3/envs/dtensor/lib/python3.8/site-packages/transformers │
│ /models/t5/modeling_t5.py:634 in __init__                                    │
│                                                                              │
│    631 │   │   super().__init__()                                            │
│    632 │   │   self.is_decoder = config.is_decoder                           ���
│    633 │   │   self.layer = nn.ModuleList()                                  │
│ ❱  634 │   │   self.layer.append(T5LayerSelfAttention(config, has_relative_a │
│    635 │   │   if self.is_decoder:                                           │
│    636 │   │   │   self.layer.append(T5LayerCrossAttention(config))          │
│    637                                                                       │
│                                                                              │
│ /home/lcfjr/miniconda3/envs/dtensor/lib/python3.8/site-packages/transformers │
│ /models/t5/modeling_t5.py:565 in __init__                                    │
│                                                                              │
│    562 │   def __init__(self, config, has_relative_attention_bias=False):    │
│    563 │   │   super().__init__()                                            │
│    564 │   │   self.SelfAttention = T5Attention(config, has_relative_attenti │
│ ❱  565 │   │   self.layer_norm = T5LayerNorm(config.d_model, eps=config.laye │
│    566 │   │   self.dropout = nn.Dropout(config.dropout_rate)                │
│    567 │                                                                     │
│    568 │   def forward(                                                      │
│                                                                              │
│ /home/lcfjr/miniconda3/envs/dtensor/lib/python3.8/site-packages/apex/normali │
│ zation/fused_layer_norm.py:364 in __init__                                   │
│                                                                              │
│   361 │   │   super().__init__()                                             │
│   362 │   │                                                                  │
│   363 │   │   global fused_layer_norm_cuda                                   │
│ ❱ 364 │   │   fused_layer_norm_cuda = importlib.import_module("fused_layer_n │
│   365 │   │                                                                  │
│   366 │   │   if isinstance(normalized_shape, numbers.Integral):             │
│   367 │   │   │   normalized_shape = (normalized_shape,)                     │
│                                                                              │
│ /home/lcfjr/miniconda3/envs/dtensor/lib/python3.8/importlib/__init__.py:127  │
│ in import_module                                                             │
│                                                                              │
│   124 │   │   │   if character != '.':                                       │
│   125 │   │   │   │   break                                                  │
│   126 │   │   │   level += 1                                                 │
│ ❱ 127 │   return _bootstrap._gcd_import(name[level:], package, level)        │
│   128                                                                        │
│   129                                                                        │
│   130 _RELOADING = {}                                                        │
│ <frozen importlib._bootstrap>:1014 in _gcd_import                            │
│ <frozen importlib._bootstrap>:991 in _find_and_load                          │
│ <frozen importlib._bootstrap>:973 in _find_and_load_unlocked                 │
╰──────────────────────────────────────────────────────────────────────────────╯
ModuleNotFoundError: No module named 'fused_layer_norm_cuda'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 4107942) of binary: /home/lcfjr/miniconda3/envs/dtensor/bin/python
Traceback (most recent call last):
  File "/home/lcfjr/miniconda3/envs/dtensor/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/lcfjr/miniconda3/envs/dtensor/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/lcfjr/miniconda3/envs/dtensor/lib/python3.8/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/home/lcfjr/miniconda3/envs/dtensor/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/lcfjr/miniconda3/envs/dtensor/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/lcfjr/miniconda3/envs/dtensor/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
colossalai_test.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-12-22_15:28:02
  host      : HPC-AI
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 4107942)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Error: failed to run torchrun --nproc_per_node=1 --nnodes=1 --node_rank=0 --rdzv_backend=c10d --rdzv_endpoint=127.0.0.1:29500 --rdzv_id=colossalai-default-job colossalai_test.py on 127.0.0.1

**Comment by theblackcat102** [comment]
I see, that's disappointing. I will test other encoder-decoder arch and see which works. 

Thanks for looking into this issue!

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
