### ISSUE TITLE
[BUG]: an instance of 'c10::CUDAErrorc10::CUDAError' initialization error

### ISSUE THREAD

**Issue by gouchangjiang** [hpcaitech/ColossalAI#2639]
### 🐛 Describe the bug

I encountered this problem when running the examples/language/gpt/titans/train_gpt.py using real data provided by the example. This probelm only occurs when we set the argument 'num_workers' of function 'get_dataloader' strictly larger than 0, say 4 in my case. It appears as soon as the end of the first epoch. I did the search on the internet. Someone says that it's because we load the data into GPU device before the dataloader. But that's not the case in the train_gpt.py. Below is the log: 
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/7204483/217466036-f7f74e0a-79d6-4ab8-a6d7-0da04ba37843.png">

### Environment

CUDA 11.3 + 1.12.1+cu113 + Colossal-AI 2.0.0 installed from github.

**Comment by JThh** [comment]
It seems that one of the workers failed:
![Uploading Screenshot 2023-02-08 at 11.10.09 PM.png…]()

**Comment by JThh** [comment]
Hello, the actual reason was when using [dummy dataset](https://github.com/hpcaitech/ColossalAI/blob/a020eecc7051083e1dbc4a02bd49a9521b032aad/examples/language/gpt/titans/dataset/webtext.py#L35), data is generated randomly and it does not make sense to use multiple workers to load data from anywhere. 

Multiple workers (hence multiple dataloaders) will support data to CUDA. And one of the subprocesses may submit data earlier than the main process, causing CUDA initialization error.

To avoid this issue, kindly download real dataset via [link](https://drive.google.com/file/d/1QKI6k-e2gJ7XgS8yIpgPPiMmwiBP_BPE/view?usp=sharing) and remove the `--use_dummy_dataset` flag.

**Comment by binmakeswell** [comment]
Hi @gouchangjiang Did you solve it? This issue was closed due to inactivity. Thanks.

**Comment by bobo0810** [comment]
> 多个工作线程（因此多个数据加载器）将支持 CUDA 的数据。并且其中一个子进程可能会比主进程更早提交数据，从而导致 CUDA 初始化错误。



@gouchangjiang @binmakeswell   Hello,  this error can be avoided by num_workers=0. However, this will slow down the data reading speed. So is there a better solution?

![image](https://github.com/hpcaitech/ColossalAI/assets/26057879/2c134020-9884-4cea-ad02-bd12a5a2f667)
