### ISSUE TITLE
[FEATURE]: BF16 support for LLM

### ISSUE THREAD

**Issue by binmakeswell** [hpcaitech/ColossalAI#3203]
### Describe the feature

Using [BF16 Optimizer](https://huggingface.co/blog/bloom-megatron-deepspeed#bf16optimizer) rather than FP16 is necessary for LLM training, which has been verified by BLOOM, OPT, and Megatron-Turing.

**Comment by kurisusnowdeng** [comment]
BF16 is much easier to use than FP16 since its range is the same as FP32, so that usually we only need to use `autocast` to wrap computation. Example usage of BF16 via both torch AMP or apex AMP could be found at my [experimental scripts](https://github.com/kurisusnowdeng/ColossalAI/tree/main/examples/language/gpt/experiments/hybrid_parallel) (torch AMP: `train_fsdp.py`; apex AMP: `train_col.py`)

**Comment by binmakeswell** [comment]
Hi @kurisusnowdeng Thanks for your insight. 

But what we need is to provide this function to users through colossalai rather than a personal experimental repo, which is actually invisible and unavailable for users. 

Can you add it officially via PRs? Thanks.
