### ISSUE TITLE
[BUG]: Regarding the supervised instructs tuning for Coati

### ISSUE THREAD

**Issue by mynamedaike** [hpcaitech/ColossalAI#3501]
### 🐛 Describe the bug

I executed the training command of supervised instructs tuning for the Coati following the instruction in the README.md. It raised the error related to NCCL as shown below. Can anyone help me with this issue? Thanks in advance.

![image](https://user-images.githubusercontent.com/14193791/230773289-c0482965-31c6-478a-8ce7-e0fef5cefa63.png)

### Environment

python==3.9.16
pytorch==1.13.1 build:py3.9_cuda11.7_cudnn8.5.0_0
pytorch-cuda==11.7
cuda-cudart==11.7.99
cuda-cupti==11.7.101
cuda-libraries==11.7.1
cuda-nvcc==12.1.66
cuda-nvcc_linux-64==11.7.1
cuda-nvrtc==11.7.99
cuda-nvtx==11.7.91
cuda-runtime==11.7.1
cudatoolkit==11.7.0
nccl==2.14.3.1

![image](https://user-images.githubusercontent.com/14193791/230772774-a91b8f22-9f0d-4258-ba52-c63ba1f0fbce.png)
![image](https://user-images.githubusercontent.com/14193791/230772795-5f3cd687-0da9-4320-8061-423090bb5896.png)
![image](https://user-images.githubusercontent.com/14193791/230772837-0ac69c24-1240-4aeb-88a4-59660a59e380.png)

**Comment by JThh** [comment]
Hi, are your GPU cards on the same machine?

**Comment by Camille7777** [comment]
hi, @mynamedaike, for the problem of "Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels", this may happen when you load or tokenize a large dataset for the first time and it takes time longer than the preset timeout time. You may try to add a timeout argument to the `Accelerator` constructor which the [default](https://github.com/huggingface/accelerate/pull/228/files#diff-0a2dccdd3480d53ead8f7643dc6fe69f4b34f7f65fff737ef188e75512db2c63R88) is 1800.
