### ISSUE TITLE
[BUG]: colossalai cannot be installed using the source code

### ISSUE THREAD

**Issue by xielinzhen** [hpcaitech/ColossalAI#4987]
### 🐛 Describe the bug

Follow these steps to install colossalai
git clone https://github.com/hpcaitech/ColossalAI.git
cd ColossalAI
pip install -r requirements/requirements.txt
CUDA_EXT=1 pip install .

the error is
`Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      1.11.1.git.kitware.jobserver-1
      g++ -pthread -B /home/pdl/anaconda3/envs/xlz/compiler_compat -shared -Wl,-rpath,/home/pdl/anaconda3/envs/xlz/lib -Wl,-rpath-link,/home/pdl/anaconda3/envs/xlz/lib -L/home/pdl/anaconda3/envs/xlz/lib -Wl,-rpath,/home/pdl/anaconda3/envs/xlz/lib -Wl,-rpath-link,/home/pdl/anaconda3/envs/xlz/lib -L/home/pdl/anaconda3/envs/xlz/lib /home/pdl/xlz/ColossalAI/build/temp.linux-x86_64-cpython-310/home/pdl/xlz/ColossalAI/colossalai/kernel/cuda_native/csrc/cpu_adam.o -L/home/pdl/anaconda3/envs/xlz/lib/python3.10/site-packages/torch/lib -L/usr/local/cuda/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda_cu -ltorch_cuda_cpp -o build/lib.linux-x86_64-cpython-310/colossalai/_C/cpu_adam.cpython-310-x86_64-linux-gnu.so
      g++: error: /home/pdl/xlz/ColossalAI/build/temp.linux-x86_64-cpython-310/home/pdl/xlz/ColossalAI/colossalai/kernel/cuda_native/csrc/cpu_adam.o: 没有那个文件或目录
      error: command '/usr/bin/g++' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for colossalai
  Running setup.py clean for colossalai
Failed to build colossalai
ERROR: Could not build wheels for colossalai, which is required to install pyproject.toml-based projects`

### Environment

cuda_11.7  
cuDNN 8904
nccl (2, 14, 3)
python 3.10
torch 1.13.1

**Comment by Orion-Zheng** [comment]
From the given information I can't locate the problem. For your information, my environment is:  
Python 3.8.17  
CUDA V11.7.64
nvidia-cudnn-cu11 8.5.0.96
torch 1.13.1
nccl (2, 14, 3)
This environment work for me at this time. You could create a virtual environment and try it out. If it still doesn't work, I think you may consider to check your environment variables, because I think the path where gcc was looking for cpu_adam.o is a bit weird:
 **/home/pdl/xlz/ColossalAI/**build/temp.linux-x86_64-cpython-310**/home/pdl/xlz/ColossalAI/colossalai/**kernel/cuda_native/csrc/cpu_adam.o
