### ISSUE TITLE
How PP and ZeRO stage 2+ work together?

### ISSUE THREAD

**Issue by hyunwoongko** [hpcaitech/ColossalAI#682]
At least as far as I know, ZeRO2 splits gradients and PP accumulates gradients, so there's no real performance boost for these two mechanisms working together.

### related issues
- https://github.com/EleutherAI/gpt-neox/issues/67
- https://github.com/EleutherAI/gpt-neox/issues/62
- https://github.com/microsoft/DeepSpeed/issues/1110

But https://github.com/hpcaitech/ColossalAI/pull/477 makes PP and ZeRO stage 2+ work together. how they are working together?

**Comment by ver217** [comment]
We currently just want to support more parallel training methods. As ZeRO and PP are both important and useful parallel training methods, we think users may want to use them together in some special cases. For example, when a layer cannot fit in the memory, like GPT-3, we must partition the layer. Absolutely, we can use TP+PP. But if the GPU memory is not enough for TP, ZeRO+PP may be another solution. As for the efficiency, we can optimize it in the future.

**Comment by ver217** [comment]
Here is an [example ](https://github.com/hpcaitech/ColossalAI-Examples/tree/main/language/gpt) of training GPT, and this is an [example config file](https://github.com/hpcaitech/ColossalAI-Examples/blob/main/language/gpt/gpt2_configs/gpt2_zero3_pp1d.py) of using ZeRO, TP and PP together.

**Comment by hyunwoongko** [comment]
Combining ZeRO2 with PP is not mechanistically efficient. ZeRO2 has to split the gradients, but PP has to accumulate the gradients, so there's no real performance boost, it's actually slower and memory inefficient than normal ZeRO2 (without PP). 

I'm saying it's inefficient to use these two algorithms together. I've been testing this for years. And it won't be easy to improve the efficiency of using the two together. To do that, one of the two would have to change in a completely new way.

**Comment by hyunwoongko** [comment]
I also don't think it makes sense for Colossal AI to use the name of `ShardedModel`. Because for ZeRO1 and 2 we don't actually split the model. This name only seems reasonable on ZeRO3.

**Comment by feifeibear** [comment]
> I also don't think it makes sense for Colossal AI to use the name of `ShardedModel`. Because for ZeRO1 and 2 we don't actually split the model. This name only seems reasonable on ZeRO3. What do you think? Of course, all of this is just advice, so feel free to do whatever you want :)

Thanks for your advice, maybe ShardableModel is more appropriate.

**Comment by Dounm** [comment]
> Combining ZeRO2 with PP is not mechanistically efficient. ZeRO2 has to split the gradients, but PP has to accumulate the gradients, so there's no real performance boost, it's actually slower and memory inefficient than normal ZeRO2 (without PP). 

@hyunwoongko Hi, I was wondering if it's possible to implement PP with ZeRO-2/3.

Say we have a model of 48L(L for Layers) to train with 2DPx4PP, which means each PP stage gets 2 devices and 12L duplicated on these 2 devs. Now I want to use torch.FSDP(which is equal to ZeRO-3 as I know) to implement the 2DP by splitting these 12L into 3 FSDP Units(each wraps 4L).

With the placement above, when dev0 forward the model,  it will allgather parameters for the 1st FSDP Unit(4L), do compute, discard the parameters and then move to the 2nd FSDP Unit(4L)。 So, at any point in time, dev0 only materializes parameters/grads only for 4L instead of 12L, thus reducing the memory peak usage.

Of course, the scheduling algorithm would be much more complicated for Pipeline with FSDP(ZeRO-3), but as a result of using FSDPxPP, we reduce the mem usage without communication overhead(the communication of FSDP can be overlapped with computation), compared with TPxPP.

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
